### ISSUE TITLE
LLama2 example always running on the CPU 

### ISSUE THREAD

**Issue by tsorman** [amd/RyzenAI-SW#70] opened 2024-04-16 04:15 UTC
I have followed the instructions to the letter when setting up the environment. 
https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/README.md

https://ryzenai.docs.amd.com/en/latest/inst.html
I can see the device on the Device Manager and driver versions are the same. 
Also when  I am running the quicktest.py I get a passes test both in the ryzen-ai-sw-1.1  and in the ryzenai-transformers environments. So I assume the NPU is present and working 
**xbutil validate -d --run verify** command is returning a PASS as well 

I have downloaded the Llama2 weights and followed the instructions in order to prepare the weights accordingly

When I am running the following script though, python run_awq.py --task decode --w_bit 4

I always get the device to be set to cpu when the decode and the benchmarks are running. 

I have gone through the Runtime setup https://ryzenai.docs.amd.com/en/latest/runtime_setup.html
set XLNX_VART_FIRMWARE=C:\path\to\1x4.xclbin
set NUM_OF_DPU_RUNNERS=1

I am not sure if I need to do anything with the Runtime Configuration File for transformers though and if yes how to do it.
Any ideas why this might be happening? 

`LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:4096, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (k_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:4096, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (v_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:4096, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (o_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:4096, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:11008, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (up_proj): ryzenAI.QLinearPerGrp(in_features:4096, out_features:11008, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (down_proj): ryzenAI.QLinearPerGrp(in_features:11008, out_features:4096, bias:torch.Size([1]), device:cpu, w_bit:4 group_size:128  )
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)`

I have tried editing the rn_awp.py to force the flags to be on the aie instead but still I got no luck there. 

The CPU I am having is AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics     3.30 GHz
and running on Windows 11 

Any help would be highly appreciated since I am not that familiar with all the peculiarities of each model

**Comment by uday610** [comment] 2024-04-16 05:30
Hi
You dont need to set XLNX_VART_FIRMWARE or other things like you shown above... You just need to follow the steps from the  repo. 
First all steps here: https://github.com/amd/RyzenAI-SW/tree/main/example/transformers 
Then all steps here: https://github.com/amd/RyzenAI-SW/tree/main/example/transformers/models/llama2 

I am not sure what you mean by "I always get the device to be set to cpu when the decode and the benchmarks are running." 

In the https://github.com/amd/RyzenAI-SW/tree/main/example/transformers/models/llama2#deployment section you can see the command to run on NPU

python run_awq.py --task decode --target aie --w_bit 4

**Comment by tsorman** [comment] 2024-04-16 05:59
hi @uday610 thanks a lot for your reply.

I am following all the steps from the 2 links you have provided 

When I am running with the command to run on the NPU 
python run_awq.py --task decode --target aie --w_bit 4    

The example is running and producing output successfully but when it displays the information of the model, I get to see this 

 ![image](https://github.com/amd/RyzenAI-SW/assets/24262070/a060dfa3-fa0a-48c9-aedf-2cf356e19c83)
note the device:cpu
 
 on the example in https://github.com/amd/RyzenAI-SW/tree/main/example/transformers/models/llama2 I can see that the out put is supposed to be like this: 
 
![image](https://github.com/amd/RyzenAI-SW/assets/24262070/198b4905-35c0-4699-885a-2480c43ef3cb)
here we see device:aie

A bit more info in case it helps:

I have used convert_llama_weights_to_hf.py using the llama2-7B-chat weights I got from HuggingFace and then I have run the checkpoints 
python run_awq.py --w_bit 4 --task quantize 
(Btw there are 4 commands there. I was not sure which to run so I only run the top one)

Again I assume this process was successful since the model runs and produces output.

I also tried with --w_bit 3 with the same results.

**Comment by uday610** [comment] 2024-04-16 06:10
There are multiple (total 7) "print(model)" in the code... Do you check the last print just before inference?

https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/models/llama2/run_awq.py#L167 

If needed, comment out all the print and just keep the one in the line 167

Yes, for quantization command: python run_awq.py --w_bit 4 --task quantize 
And to run it : python run_awq.py --task decode --target aie --w_bit 4

**Comment by tsorman** [comment] 2024-04-16 06:19
I have commented out all but the one you pointed out.

I can see that the device is npu now.

![image](https://github.com/amd/RyzenAI-SW/assets/24262070/249713b7-c9c0-4978-89f5-4ab2456f4ee4)

I did run the quantization in again in the meantime so I am not sure if that made a difference or I skipped this part on the logs. 
Thanks for the help.

**Comment by uday610** [comment] 2024-04-22 17:05
Assuming the issue is fixed, closing this

**Closed by uday610** 2024-04-22 17:05 UTC
