### ISSUE TITLE
I could not make Ryzen AI work with AMD 8600G, please help.

### ISSUE THREAD

**Issue by onurilericiler** [amd/RyzenAI-SW#59] opened 2024-03-05 06:59 UTC
![anydesk00000](https://github.com/amd/RyzenAI-SW/assets/111572367/dc8114e0-2f36-4b48-a963-8ff3c65e255d)
![anydesk00002](https://github.com/amd/RyzenAI-SW/assets/111572367/e47ffba0-b993-4bc6-8eb6-7fc5e8773562)

quicktest.py says test passed, but hello world jupiter file gives a bunch of errors on the ipu section.

**Comment by shivani-athavale** [comment] 2024-03-05 19:01
Hello @onurilericiler,
 
Please try running "**pip install jupyter**" to solve the issue you are facing with the hello world notebook.
 
_Summarizing below the flow that needs to be followed to get the hello world tutorial running:_
 
Follow the instructions here Installation Instructions — Ryzen AI Software 1.0.1 [documentation](https://ryzenai.docs.amd.com/en/latest/inst.html)
 
```
conda activate ryzenai_installation_created_env
git clone https://github.com/amd/RyzenAI-SW.git
cd tutorial/hello_world
pip install jupyter
```
Then you can open the hello_world tutorial ipynb and it should work fine

**Comment by onurilericiler** [comment] 2024-03-06 13:55
Hi @shivani-athavale thank you for the kind response. I did the conda setup from scratch with your recommendation but, I still get the same error. Any other recommendations please?

RuntimeException                          Traceback (most recent call last)
Cell In[6], [line 9](vscode-notebook-cell:?execution_count=6&line=9)
      [6](vscode-notebook-cell:?execution_count=6&line=6) aie_options = onnxruntime.SessionOptions()
      [7](vscode-notebook-cell:?execution_count=6&line=7) aie_options.enable_profiling = True
----> [9](vscode-notebook-cell:?execution_count=6&line=9) aie_session = onnxruntime.InferenceSession(
     [10](vscode-notebook-cell:?execution_count=6&line=10)     onnx_model_path,
     [11](vscode-notebook-cell:?execution_count=6&line=11)     providers = ['VitisAIExecutionProvider'],
     [12](vscode-notebook-cell:?execution_count=6&line=12)     sess_options=aie_options,
     [13](vscode-notebook-cell:?execution_count=6&line=13)     provider_options=[{'config_file': config_file_path}]
     [14](vscode-notebook-cell:?execution_count=6&line=14) )
     [16](vscode-notebook-cell:?execution_count=6&line=16) start = timer()
     [17](vscode-notebook-cell:?execution_count=6&line=17) ryzen_outputs = aie_session.run(None, {'input': input_data})

File [c:\Users\user\miniconda3\envs\ryzenai-1.1-20240306-164050\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:383](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:383), in InferenceSession.__init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    [380](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:380) disabled_optimizers = kwargs["disabled_optimizers"] if "disabled_optimizers" in kwargs else None
    [382](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:382) try:
--> [383](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:383)     self._create_inference_session(providers, provider_options, disabled_optimizers)
    [384](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:384) except (ValueError, RuntimeError) as e:
    [385](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:385)     if self._enable_fallback:

File [c:\Users\user\miniconda3\envs\ryzenai-1.1-20240306-164050\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:435](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:435), in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    [432](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:432)     disabled_optimizers = set(disabled_optimizers)
    [434](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:434) # initialize the C++ InferenceSession
--> [435](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:435) sess.initialize_session(providers, provider_options, disabled_optimizers)
    [437](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:437) self._sess = sess
    [438](file:///C:/Users/user/miniconda3/envs/ryzenai-1.1-20240306-164050/lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:438) self._sess_options = self._sess.session_options

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: CHECK failed: it != end(): key not found: profile

**Comment by vgodsoe** [comment] 2024-03-07 15:35
Hi @onurilericiler, 

It looks like the issue occurs during the quantization step. The option `enable_dpu` is being deprecated and the updated option is `enable_ipu_cnn`. I've included a snippet of the updated code for convenience. 

```python
vai_q_onnx.quantize_static(
    input_model_path,
    output_model_path,
    calibration_data_reader=None,
    quant_format=QuantFormat.QDQ,
    calibrate_method=vai_q_onnx.PowerOfTwoMethod.MinMSE,
    activation_type=QuantType.QInt8,
    weight_type=QuantType.QInt8,
    enable_ipu_cnn=True,
    extra_options={'ActivationSymmetric': True}
)
```

I tested that this works but let us know if you run into any issues and we'd be happy to help.
Thank you for bringing this to our attention. We'll get the example tutorial updated with this fix.

Thanks,
Victoria

**Comment by onurilericiler** [comment] 2024-03-08 06:49
Hi @vgodsoe thank you for the update but enable_ipu_cnn did not make it on my side. I adapted the code from quicktest.py,  hello_world.ipynb should be next to voe-4.0-win_amd64 to avoid path errors.

CPU Total Time: 0.0003987000000016394
IPU Total Time: 0.00014640000000021303

# Compile and run
import os
import onnxruntime as ort
import numpy as np
from timeit import default_timer as timer
from pathlib import Path

# Specify the path to the quantized ONNZ Model
model = "models/helloworld_quantized.onnx"

# Create some random input data for testing
input_data = np.random.uniform(low=-1, high=1, size=[1,10]).astype(np.float32)

# realtive Path to the voe-4.0-win_amd64 directory
path = os.path.join(os.getcwd(), 'voe-4.0-win_amd64')
# Specify the provider as VitisAIExecutionProvider
providers = ['VitisAIExecutionProvider']
# Resolve the cache directory path relative to this jupyter file
cache_dir = Path(os.path.join(os.getcwd(), 'cache'))
# Provider options including the path to the config file, cache directory, and a cache key
provider_options = [{
            'config_file': os.path.join('..', path, 'vaip_config.json'),  # Adjust the config file path as necessary
            'cacheDir': str(cache_dir),  # Convert the cache directory Path object to string
            'cacheKey': 'modelcachekey_quick'
        }]


aie_session = ort.InferenceSession(model, providers=providers,
                                   provider_options=provider_options)

start = timer()
ryzen_outputs = aie_session.run(None, {'input': input_data})
aie_total = timer() - start

aie_session.end_profiling()

**Comment by uday610** [comment] 2024-03-18 10:20
Hi @onurilericiler , it sounds like the issue is resolved for you. Hence closing the ticket

**Closed by uday610** 2024-03-18 10:20 UTC

**Comment by onurilericiler** [comment] 2024-03-19 09:05
Thank you @uday610, LM studio gives easier handling but, I am not sure about the performance, is there any benchmark data in hand?
