### ISSUE TITLE
IPU Driver updates and environment installation

### ISSUE THREAD

**Issue by ocwins** [amd/RyzenAI-SW#47] opened 2023-12-08 08:52 UTC
I have played Ryzen AI Software version 1.0 for a little while.

It seems that the [automatic installation script](https://ryzenai.docs.amd.com/en/latest/inst.html#install-bundled) doesn't execute `python installer.py`, so the necessary dlls won't be copied into the directory where python is installed on windows.

And there are some more questions.

Shall we periodically check the [page](https://ryzenai.docs.amd.com/en/latest/inst.html) and manually update the IPU driver, or can we just leave it to 'AMD Software: Adrenalin Edition' (or windows update)?

I followed the instruction from the page and manually updated the IPU driver this time, because I don't know How to update it using Adrenalin. Will the AMD Software update the IPU driver automatically? 

Are there different plans for different users, like, developers and consumers should use different drivers at moment ? I suggest making these things clarified.

Thank you. @poganesh

**Comment by uday610** [comment] 2023-12-08 17:38
Hi @ocwins , 

I am not sure why you are saying installer.py is not executing, if it is not executed you could not run any examples. For example, if you run the automatic installer in conda environment the output should be like below showing excuring installer.py and copying the DLL files. 

```
Executing installer.py ...
2023-12-08 09:23:35,485 - INFO - copying C:\Windows\System32\AMD\xrt_core.dll to C:\Users\xbuild\anaconda3\envs\ryzenai-1.0-20231208-092154\lib\site-packages\onnxruntime\capi
2023-12-08 09:23:35,497 - INFO - copying C:\Windows\System32\AMD\xrt_coreutil.dll to C:\Users\xbuild\anaconda3\envs\ryzenai-1.0-20231208-092154\lib\site-packages\onnxruntime\capi
2023-12-08 09:23:35,497 - CRITICAL - C:\Windows\System32\AMD\amd_xrt_core.dll does not exist.
2023-12-08 09:23:35,497 - INFO - copying C:\Users\xbuild\Downloads\ryzen-ai-sw-1.0\ryzen-ai-sw-1.0\voe-4.0-win_amd64\voe-0.1.0-cp39-cp39-win_amd64\onnxruntime.dll to C:\Users\xbuild\anaconda3\envs\ryzenai-1.0-20231208-092154\lib\site-packages\onnxruntime\capi
```

We do have plans to release IPU driver bundled with Adrenalin in future releases. We will finalize these details and inform. 

Thanks

**Comment by ocwins** [comment] 2023-12-08 20:50
Hi @uday610 ，  

Certainly I could not run any model examples at first, then I executed installer.py manually, so I knew it was not executed automatically.

I executed automatic installation (bat file) it failed once or twice for some reason (one of them was CMake not installed), it finally succeeded after problems were solved. When I ran the quicktest without success, I found the DLLs were not copied. I guess these info is not so helpful.

You might close this issue. I don't think I could provide more details soon before I have time to investigate this again.

**Comment by uday610** [comment] 2023-12-09 14:31
@ocwins: 
>> " it finally succeeded after problems were solved" 
I am not sure how it completed successfully when it could not copy the files. We will keep an eye, but I dont think we have enough information to understand the root cause. I will close this ticket as you suggested. 
Thank yoy

**Closed by uday610** 2023-12-09 14:31 UTC
