### ISSUE TITLE
Would add some document to explain how to install RyzenAI SW to existed docker container，or how to install on linunx

### ISSUE THREAD

**Issue by joebnb** [amd/RyzenAI-SW#106] opened 2024-07-17 07:41 UTC
TLDR

there have no documents to tell how to  install  ryzen ai to use on linux, i want use amd npu to accelerate ai computing,but did konw how to make it works

**Comment by joebnb** [comment] 2024-07-17 10:03
https://hub.docker.com/r/intel/intel-optimized-pytorch seems intel take advantage alot

**Comment by uday610** [comment] 2024-07-24 14:55
duplicate of issue #2

**Comment by uday610** [comment] 2024-07-31 00:04
closed as duplicate

**Closed by uday610** 2024-07-31 00:04 UTC
